import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'or';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.matches': 'Matches',
    'nav.applications': 'Applications',
    'nav.saved': 'Saved',
    'nav.logout': 'Logout',
    'hero.title': 'Earn Your Future',
    'hero.subtitle': 'AI-powered platform that matches eligible students with government and private scholarships.',
    'hero.cta': 'Find Scholarships Now',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.welcome': 'Welcome',
    'auth.create': 'Create Account',
    'dashboard.welcome': 'Welcome back',
    'dashboard.matches': 'New Matches',
    'dashboard.deadlines': 'Upcoming Deadlines',
    'dashboard.saved': 'Saved Scholarships',
    'dashboard.totalMatches': 'Total Matches',
    'dashboard.applications': 'Applications',
    'dashboard.viewAll': 'View All',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noActivity': 'No recent activity.',
    'landing.badge': 'Global Scholarship Search Engine',
    'landing.title1': 'Your Education,',
    'landing.title2': 'Fully Funded.',
    'landing.desc1': 'We use advanced AI to scan worldwide government and private databases in real-time.',
    'landing.desc2': 'Complete your profile below to unlock personalized funding opportunities.',
    'landing.f1.title': 'Global Reach',
    'landing.f1.desc': 'Access scholarships from 190+ countries instantly.',
    'landing.f2.title': 'AI Precision',
    'landing.f2.desc': 'Smart matching based on your unique story and goals.',
    'landing.f3.title': 'Career First',
    'landing.f3.desc': 'Funding that aligns with your professional dreams.',
    'profile.title': 'Complete Your Profile',
    'profile.subtitle': 'Tell us about yourself to find the best scholarship matches.',
    'profile.personal': 'Personal Details',
    'profile.education': 'Education',
    'profile.location': 'Location',
    'profile.demographics': 'Demographics',
    'profile.academic': 'Academic Performance',
    'profile.next': 'Next Step',
    'profile.back': 'Back',
    'profile.submit': 'Find My Matches',
    'profile.saving': 'Saving...',
    'scholarship.match': 'Match',
    'scholarship.deadline': 'Deadline',
    'scholarship.amount': 'Amount',
    'scholarship.apply': 'Apply Now',
    'scholarship.save': 'Save',
    'scholarship.saved': 'Saved',
    'scholarship.viewDetails': 'View Details',
    'scholarship.less': 'Less',
    'scholarship.details': 'Details',
    'scholarship.share': 'Share',
    'scholarship.copied': 'Copied!',
    'scholarship.remind': 'Remind',
    'scholarship.setReminder': 'Set Reminder',
    'scholarship.reminderSet': 'Reminder Set',
    'scholarship.notes': 'Notes',
    'scholarship.addNotes': 'Add Notes',
    'scholarship.saveNotes': 'Save Notes',
    'scholarship.cancel': 'Cancel',
    'scholarship.excellentMatch': 'Excellent Match',
    'scholarship.goodMatch': 'Good Match',
    'scholarship.potentialMatch': 'Potential Match',
    'scholarship.pastDeadline': 'Past Deadline',
    'scholarship.applied': 'Applied',
    'scholarship.inProgress': 'In Progress',
    'scholarship.awarded': 'Awarded',
    'scholarship.notAwarded': 'Not Awarded',
    'scholarship.approx': 'Approx.',
    'scholarship.local': 'Local',
    'scholarship.provider': 'Provider',
    'scholarship.minGpa': 'Minimum GPA Required',
    'scholarship.specificLocation': 'Specific Location',
    'scholarship.fullDescription': 'Full Description',
    'scholarship.eligibilityCriteria': 'Eligibility Criteria',
    'scholarship.thingsRequired': 'Things Required for Applying',
    'scholarship.whyGoodMatch': 'Why this is a good match',
    'scholarship.missingRequirements': 'Missing Requirements',
    'scholarship.updateStatus': 'Update Status',
    'scholarship.status.applied': 'Applied',
    'scholarship.status.inProgress': 'In Progress',
    'scholarship.status.awarded': 'Awarded',
    'scholarship.status.rejected': 'Not Awarded',
    'scholarship.status.saved': 'Saved',
    'scholarship.status.none': 'None',
    'scholarship.set': 'Set',
    'scholarship.aiMatchAnalysis': 'AI Match Analysis',
    'scholarship.excellent': 'Excellent',
    'scholarship.good': 'Good',
    'scholarship.fair': 'Fair',
    'scholarship.linkNotWorking': 'Link not working?',
    'scholarship.searchGoogle': 'Search for this scholarship on Google',
    'scholarship.deadlinePassed': 'Deadline Passed',
    'scholarship.visitPortal': 'Visit Portal',
    'dashboard.title': 'Interest Dashboard',
    'dashboard.subtitle': 'Visualizing your scholarship journey and AI-detected interests.',
    'applications.title': 'My Applications',
    'applications.subtitle': 'Tracking {count} scholarships you\'ve started or completed.',
    'applications.back': 'Back to All Matches',
    'applications.empty.title': 'No Applications Yet',
    'applications.empty.desc': 'Start exploring matches and click "Apply Now" to track them here.',
    'applications.empty.btn': 'Explore Scholarships',
    'saved.title': 'Saved Scholarships',
    'saved.subtitle': 'You have {count} scholarships saved for later.',
    'saved.back': 'Back to All Matches',
    'saved.empty.title': 'No Saved Scholarships',
    'saved.empty.desc': 'Click the heart icon on any scholarship to save it for later.',
    'saved.empty.btn': 'Find Scholarships',
    'results.found': 'Found',
    'results.opportunities': 'Opportunities',
    'results.matchesFor': 'Matches for {name} in {country}',
    'results.searchPlaceholder': 'Search keywords...',
    'results.refresh': 'Refresh search results',
    'results.filters': 'Filters',
    'results.hideFilters': 'Hide',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.matches': 'मैच',
    'nav.applications': 'आवेदन',
    'nav.saved': 'सहेजा गया',
    'nav.logout': 'लॉग आउट',
    'hero.title': 'अपना भविष्य संवारें',
    'hero.subtitle': 'एआई-संचालित मंच जो योग्य छात्रों को सरकारी और निजी छात्रवृत्ति से मिलाता है।',
    'hero.cta': 'अभी छात्रवृत्ति खोजें',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.name': 'पूरा नाम',
    'auth.phone': 'फ़ोन नंबर',
    'auth.welcome': 'स्वागत है',
    'auth.create': 'खाता बनाएं',
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.matches': 'नए मैच',
    'dashboard.deadlines': 'आगामी समय सीमा',
    'dashboard.saved': 'सहेजी गई छात्रवृत्ति',
    'dashboard.totalMatches': 'कुल मैच',
    'dashboard.applications': 'आवेदन',
    'dashboard.viewAll': 'सभी देखें',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    'dashboard.noActivity': 'कोई हाल की गतिविधि नहीं।',
    'landing.badge': 'वैश्विक छात्रवृत्ति खोज इंजन',
    'landing.title1': 'आपकी शिक्षा,',
    'landing.title2': 'पूरी तरह से वित्त पोषित।',
    'landing.desc1': 'हम वास्तविक समय में दुनिया भर के सरकारी और निजी डेटाबेस को स्कैन करने के लिए उन्नत एआई का उपयोग करते हैं।',
    'landing.desc2': 'व्यक्तिगत फंडिंग अवसरों को अनलॉक करने के लिए नीचे अपना प्रोफ़ाइल पूरा करें।',
    'landing.f1.title': 'वैश्विक पहुंच',
    'landing.f1.desc': '190+ देशों से तुरंत छात्रवृत्ति प्राप्त करें।',
    'landing.f2.title': 'एआई सटीकता',
    'landing.f2.desc': 'आपकी अनूठी कहानी और लक्ष्यों के आधार पर स्मार्ट मिलान।',
    'landing.f3.title': 'करियर प्रथम',
    'landing.f3.desc': 'फंडिंग जो आपके पेशेवर सपनों के साथ मेल खाती है।',
    'profile.title': 'अपनी प्रोफ़ाइल पूरी करें',
    'profile.subtitle': 'सर्वश्रेष्ठ छात्रवृत्ति मैच खोजने के लिए हमें अपने बारे में बताएं।',
    'profile.personal': 'व्यक्तिगत विवरण',
    'profile.education': 'शिक्षा',
    'profile.location': 'स्थान',
    'profile.demographics': 'जनसांख्यिकी',
    'profile.academic': 'शैक्षणिक प्रदर्शन',
    'profile.next': 'अगला कदम',
    'profile.back': 'पीछे',
    'profile.submit': 'मेरे मैच खोजें',
    'profile.saving': 'सहेजा जा रहा है...',
    'scholarship.match': 'मैच',
    'scholarship.deadline': 'समय सीमा',
    'scholarship.amount': 'राशि',
    'scholarship.apply': 'अभी आवेदन करें',
    'scholarship.save': 'सहेजें',
    'scholarship.saved': 'सहेजा गया',
    'scholarship.viewDetails': 'विवरण देखें',
    'scholarship.less': 'कम',
    'scholarship.details': 'विवरण',
    'scholarship.share': 'साझा करें',
    'scholarship.copied': 'कॉपी किया गया!',
    'scholarship.remind': 'याद दिलाएं',
    'scholarship.setReminder': 'रिमाइंडर सेट करें',
    'scholarship.reminderSet': 'रिमाइंडर सेट किया गया',
    'scholarship.notes': 'नोट्स',
    'scholarship.addNotes': 'नोट्स जोड़ें',
    'scholarship.saveNotes': 'नोट्स सहेजें',
    'scholarship.cancel': 'रद्द करें',
    'scholarship.excellentMatch': 'उत्कृष्ट मैच',
    'scholarship.goodMatch': 'अच्छा मैच',
    'scholarship.potentialMatch': 'संभावित मैच',
    'scholarship.pastDeadline': 'समय सीमा समाप्त',
    'scholarship.applied': 'लागू',
    'scholarship.inProgress': 'प्रगति पर',
    'scholarship.awarded': 'प्रदान किया गया',
    'scholarship.notAwarded': 'प्रदान नहीं किया गया',
    'scholarship.approx': 'लगभग',
    'scholarship.local': 'स्थानीय',
    'scholarship.provider': 'प्रदाता',
    'scholarship.minGpa': 'न्यूनतम जीपीए आवश्यक',
    'scholarship.specificLocation': 'विशिष्ट स्थान',
    'scholarship.fullDescription': 'पूर्ण विवरण',
    'scholarship.eligibilityCriteria': 'पात्रता मापदंड',
    'scholarship.thingsRequired': 'आवेदन के लिए आवश्यक चीजें',
    'scholarship.whyGoodMatch': 'यह एक अच्छा मैच क्यों है',
    'scholarship.missingRequirements': 'लापता आवश्यकताएं',
    'scholarship.updateStatus': 'स्थिति अपडेट करें',
    'scholarship.status.applied': 'लागू',
    'scholarship.status.inProgress': 'प्रगति पर',
    'scholarship.status.awarded': 'प्रदान किया गया',
    'scholarship.status.rejected': 'प्रदान नहीं किया गया',
    'scholarship.status.saved': 'सहेजा गया',
    'scholarship.status.none': 'कोई नहीं',
    'scholarship.set': 'सेट करें',
    'scholarship.aiMatchAnalysis': 'एआई मैच विश्लेषण',
    'scholarship.excellent': 'उत्कृष्ट',
    'scholarship.good': 'अच्छा',
    'scholarship.fair': 'निष्पक्ष',
    'scholarship.linkNotWorking': 'लिंक काम नहीं कर रहा है?',
    'scholarship.searchGoogle': 'Google पर इस छात्रवृत्ति को खोजें',
    'scholarship.deadlinePassed': 'समय सीमा समाप्त',
    'scholarship.visitPortal': 'पोर्टल पर जाएं',
    'dashboard.title': 'रुचि डैशबोर्ड',
    'dashboard.subtitle': 'आपकी छात्रवृत्ति यात्रा और एआई-पता लगाए गए रुचियों की कल्पना करना।',
    'applications.title': 'मेरे आवेदन',
    'applications.subtitle': 'आपके द्वारा शुरू या पूर्ण की गई {count} छात्रवृत्तियों को ट्रैक करना।',
    'applications.back': 'सभी मैचों पर वापस जाएं',
    'applications.empty.title': 'अभी तक कोई आवेदन नहीं',
    'applications.empty.desc': 'मैचों की खोज शुरू करें और उन्हें यहां ट्रैक करने के लिए "अभी आवेदन करें" पर क्लिक करें।',
    'applications.empty.btn': 'छात्रवृत्तियों का अन्वेषण करें',
    'saved.title': 'सहेजी गई छात्रवृत्तियां',
    'saved.subtitle': 'आपके पास बाद के लिए {count} छात्रवृत्तियां सहेजी गई हैं।',
    'saved.back': 'सभी मैचों पर वापस जाएं',
    'saved.empty.title': 'कोई सहेजी गई छात्रवृत्ति नहीं',
    'saved.empty.desc': 'किसी भी छात्रवृत्ति को बाद के लिए सहेजने के लिए उस पर दिल के आइकन पर क्लिक करें।',
    'saved.empty.btn': 'छात्रवृत्तियां खोजें',
    'results.found': 'मिले',
    'results.opportunities': 'अवसर',
    'results.matchesFor': '{country} में {name} के लिए मैच',
    'results.searchPlaceholder': 'कीवर्ड खोजें...',
    'results.refresh': 'खोज परिणाम रीफ्रेश करें',
    'results.filters': 'फ़िल्टर',
    'results.hideFilters': 'छिपाएं',
  },
  or: {
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.profile': 'ପ୍ରୋଫାଇଲ୍',
    'nav.matches': 'ମେଳକ',
    'nav.applications': 'ଆବେଦନ',
    'nav.saved': 'ସଂରକ୍ଷିତ',
    'nav.logout': 'ଲଗ୍ ଆଉଟ୍',
    'hero.title': 'ଆପଣଙ୍କର ଭବିଷ୍ୟତ ଗଢ଼ନ୍ତୁ',
    'hero.subtitle': 'ଏଆଇ-ଚାଳିତ ପ୍ଲାଟଫର୍ମ ଯାହା ଯୋଗ୍ୟ ଛାତ୍ରମାନଙ୍କୁ ସରକାରୀ ଏବଂ ବେସରକାରୀ ବୃତ୍ତି ସହିତ ମେଳ କରେ |',
    'hero.cta': 'ବର୍ତ୍ତମାନ ବୃତ୍ତି ଖୋଜନ୍ତୁ',
    'auth.signin': 'ସାଇନ୍ ଇନ୍',
    'auth.signup': 'ସାଇନ୍ ଅପ୍',
    'auth.email': 'ଇମେଲ୍ ଠିକଣା',
    'auth.password': 'ପାସୱାର୍ଡ',
    'auth.name': 'ପୁରା ନାମ',
    'auth.phone': 'ଫୋନ୍ ନମ୍ବର',
    'auth.welcome': 'ସ୍ୱାଗତ',
    'auth.create': 'ଆକାଉଣ୍ଟ୍ ସୃଷ୍ଟି କରନ୍ତୁ',
    'dashboard.welcome': 'ପୁନର୍ବାର ସ୍ୱାଗତ',
    'dashboard.matches': 'ନୂତନ ମେଳକ',
    'dashboard.deadlines': 'ଆଗାମୀ ସମୟସୀମା',
    'dashboard.saved': 'ସଂରକ୍ଷିତ ବୃତ୍ତି',
    'dashboard.totalMatches': 'ମୋଟ ମେଳକ',
    'dashboard.applications': 'ଆବେଦନ',
    'dashboard.viewAll': 'ସବୁ ଦେଖନ୍ତୁ',
    'dashboard.recentActivity': 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    'dashboard.noActivity': 'କୌଣସି ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ ନାହିଁ |',
    'landing.badge': 'ଗ୍ଲୋବାଲ୍ ସ୍କଲାରସିପ୍ ସର୍ଚ୍ଚ ଇଞ୍ଜିନ୍',
    'landing.title1': 'ଆପଣଙ୍କର ଶିକ୍ଷା,',
    'landing.title2': 'ସମ୍ପୂର୍ଣ୍ଣ ଅର୍ଥପ୍ରାପ୍ତ |',
    'landing.desc1': 'ଆମେ ବାସ୍ତବ ସମୟରେ ବିଶ୍ୱବ୍ୟାପୀ ସରକାରୀ ଏବଂ ବେସରକାରୀ ଡାଟାବେସ୍ ସ୍କାନ୍ କରିବାକୁ ଉନ୍ନତ ଏଆଇ ବ୍ୟବହାର କରୁ |',
    'landing.desc2': 'ବ୍ୟକ୍ତିଗତ ପାଣ୍ଠି ସୁଯୋଗ ଅନଲକ୍ କରିବାକୁ ତଳେ ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ |',
    'landing.f1.title': 'ବିଶ୍ୱବ୍ୟାପୀ ପହଞ୍ଚ',
    'landing.f1.desc': '190+ ଦେଶରୁ ତୁରନ୍ତ ବୃତ୍ତି ପ୍ରାପ୍ତ କରନ୍ତୁ |',
    'landing.f2.title': 'ଏଆଇ ସଠିକତା',
    'landing.f2.desc': 'ଆପଣଙ୍କର ଅନନ୍ୟ କାହାଣୀ ଏବଂ ଲକ୍ଷ୍ୟ ଉପରେ ଆଧାର କରି ସ୍ମାର୍ଟ ମେଳକ |',
    'landing.f3.title': 'ପ୍ରଥମେ କ୍ୟାରିୟର୍',
    'landing.f3.desc': 'ପାଣ୍ଠି ଯାହା ଆପଣଙ୍କର ବୃତ୍ତିଗତ ସ୍ୱପ୍ନ ସହିତ ସମାନ |',
    'profile.title': 'ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
    'profile.subtitle': 'ସର୍ବୋତ୍ତମ ବୃତ୍ତି ମେଳକ ଖୋଜିବାକୁ ଆମକୁ ଆପଣଙ୍କ ବିଷୟରେ କୁହନ୍ତୁ |',
    'profile.personal': 'ବ୍ୟକ୍ତିଗତ ବିବରଣୀ',
    'profile.education': 'ଶିକ୍ଷା',
    'profile.location': 'ସ୍ଥାନ',
    'profile.demographics': 'ଜନସଂଖ୍ୟା',
    'profile.academic': 'ଏକାଡେମିକ୍ ପ୍ରଦର୍ଶନ',
    'profile.next': 'ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ',
    'profile.back': 'ପଛକୁ',
    'profile.submit': 'ମୋର ମେଳକ ଖୋଜନ୍ତୁ',
    'profile.saving': 'ସଞ୍ଚୟ ହେଉଛି...',
    'scholarship.match': 'ମେଳକ',
    'scholarship.deadline': 'ସମୟସୀମା',
    'scholarship.amount': 'ପରିମାଣ',
    'scholarship.apply': 'ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ',
    'scholarship.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    'scholarship.saved': 'ସଂରକ୍ଷିତ',
    'scholarship.viewDetails': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    'scholarship.less': 'କମ୍',
    'scholarship.details': 'ବିବରଣୀ',
    'scholarship.share': 'ସେୟାର କରନ୍ତୁ',
    'scholarship.copied': 'କପି ହୋଇଛି!',
    'scholarship.remind': 'ମନେ ପକାନ୍ତୁ',
    'scholarship.setReminder': 'ରିମାଇଣ୍ଡର ସେଟ୍ କରନ୍ତୁ',
    'scholarship.reminderSet': 'ରିମାଇଣ୍ଡର ସେଟ୍ ହୋଇଛି',
    'scholarship.notes': 'ନୋଟ୍ସ',
    'scholarship.addNotes': 'ନୋଟ୍ସ ଯୋଡନ୍ତୁ',
    'scholarship.saveNotes': 'ନୋଟ୍ସ ସେଭ୍ କରନ୍ତୁ',
    'scholarship.cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
    'scholarship.excellentMatch': 'ଉତ୍କୃଷ୍ଟ ମ୍ୟାଚ୍',
    'scholarship.goodMatch': 'ଭଲ ମ୍ୟାଚ୍',
    'scholarship.potentialMatch': 'ସମ୍ଭାବ୍ୟ ମ୍ୟାଚ୍',
    'scholarship.pastDeadline': 'ସମୟ ସୀମା ଶେଷ',
    'scholarship.applied': 'ଆବେଦନ କରାଯାଇଛି',
    'scholarship.inProgress': 'ଚାଲିଛି',
    'scholarship.awarded': 'ପ୍ରଦାନ କରାଯାଇଛି',
    'scholarship.notAwarded': 'ପ୍ରଦାନ କରାଯାଇନାହିଁ',
    'scholarship.approx': 'ପାଖାପାଖି',
    'scholarship.local': 'ସ୍ଥାନୀୟ',
    'scholarship.provider': 'ପ୍ରଦାନକାରୀ',
    'scholarship.minGpa': 'ସର୍ବନିମ୍ନ ଜିପିଏ ଆବଶ୍ୟକ',
    'scholarship.specificLocation': 'ନିର୍ଦ୍ଦିଷ୍ଟ ସ୍ଥାନ',
    'scholarship.fullDescription': 'ସମ୍ପୂର୍ଣ୍ଣ ବିବରଣୀ',
    'scholarship.eligibilityCriteria': 'ଯୋଗ୍ୟତା ମାନଦଣ୍ଡ',
    'scholarship.thingsRequired': 'ଆବେଦନ ପାଇଁ ଆବଶ୍ୟକ ଜିନିଷ',
    'scholarship.whyGoodMatch': 'ଏହା କାହିଁକି ଏକ ଭଲ ମ୍ୟାଚ୍',
    'scholarship.missingRequirements': 'ଅନୁପସ୍ଥିତ ଆବଶ୍ୟକତା',
    'scholarship.updateStatus': 'ସ୍ଥିତି ଅପଡେଟ୍ କରନ୍ତୁ',
    'scholarship.status.applied': 'ଆବେଦନ କରାଯାଇଛି',
    'scholarship.status.inProgress': 'ଚାଲିଛି',
    'scholarship.status.awarded': 'ପ୍ରଦାନ କରାଯାଇଛି',
    'scholarship.status.rejected': 'ପ୍ରଦାନ କରାଯାଇନାହିଁ',
    'scholarship.status.saved': 'ସେଭ୍ ହୋଇଛି',
    'scholarship.status.none': 'କିଛି ନୁହେଁ',
    'scholarship.set': 'ସେଟ୍ କରନ୍ତୁ',
    'scholarship.aiMatchAnalysis': 'ଏଆଇ ମ୍ୟାଚ୍ ବିଶ୍ଳେଷଣ',
    'scholarship.excellent': 'ଉତ୍କୃଷ୍ଟ',
    'scholarship.good': 'ଭଲ',
    'scholarship.fair': 'ସାଧାରଣ',
    'scholarship.linkNotWorking': 'ଲିଙ୍କ୍ କାମ କରୁନାହିଁ କି?',
    'scholarship.searchGoogle': 'ଗୁଗୁଲରେ ଏହି ବୃତ୍ତି ଖୋଜନ୍ତୁ',
    'scholarship.deadlinePassed': 'ସମୟ ସୀମା ଶେଷ',
    'scholarship.visitPortal': 'ପୋର୍ଟାଲ୍ ପରିଦର୍ଶନ କରନ୍ତୁ',
    'dashboard.title': 'ଆଗ୍ରହ ଡ୍ୟାସବୋର୍ଡ',
    'dashboard.subtitle': 'ଆପଣଙ୍କର ବୃତ୍ତି ଯାତ୍ରା ଏବଂ ଏଆଇ-ଚିହ୍ନଟ ଆଗ୍ରହକୁ ଭିଜୁଆଲାଇଜ୍ କରିବା |',
    'applications.title': 'ମୋର ଆବେଦନ',
    'applications.subtitle': 'ଆପଣ ଆରମ୍ଭ କିମ୍ବା ଶେଷ କରିଥିବା {count} ବୃତ୍ତିଗୁଡ଼ିକୁ ଟ୍ରାକ୍ କରିବା |',
    'applications.back': 'ସମସ୍ତ ମ୍ୟାଚ୍ କୁ ଫେରନ୍ତୁ',
    'applications.empty.title': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆବେଦନ ନାହିଁ',
    'applications.empty.desc': 'ମ୍ୟାଚ୍ ଅନୁସନ୍ଧାନ ଆରମ୍ଭ କରନ୍ତୁ ଏବଂ ସେଗୁଡିକୁ ଏଠାରେ ଟ୍ରାକ୍ କରିବାକୁ "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ" ରେ କ୍ଲିକ୍ କରନ୍ତୁ |',
    'applications.empty.btn': 'ବୃତ୍ତି ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
    'saved.title': 'ସେଭ୍ ହୋଇଥିବା ବୃତ୍ତି',
    'saved.subtitle': 'ଆପଣଙ୍କ ପାଖରେ ପରେ ପାଇଁ {count} ବୃତ୍ତି ସେଭ୍ ହୋଇଛି |',
    'saved.back': 'ସମସ୍ତ ମ୍ୟାଚ୍ କୁ ଫେରନ୍ତୁ',
    'saved.empty.title': 'କୌଣସି ସେଭ୍ ହୋଇଥିବା ବୃତ୍ତି ନାହିଁ',
    'saved.empty.desc': 'ଯେକୌଣସି ବୃତ୍ତିକୁ ପରେ ସେଭ୍ କରିବାକୁ ସେଥିରେ ଥିବା ହାର୍ଟ ଆଇକନ୍ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ |',
    'saved.empty.btn': 'ବୃତ୍ତି ଖୋଜନ୍ତୁ',
    'results.found': 'ମିଳିଲା',
    'results.opportunities': 'ସୁଯୋଗ',
    'results.matchesFor': '{country} ରେ {name} ପାଇଁ ମ୍ୟାଚ୍',
    'results.searchPlaceholder': 'କୀୱାର୍ଡ ଖୋଜନ୍ତୁ...',
    'results.refresh': 'ସନ୍ଧାନ ଫଳାଫଳ ରିଫ୍ରେସ୍ କରନ୍ତୁ',
    'results.filters': 'ଫିଲ୍ଟର୍',
    'results.hideFilters': 'ଲୁଚାନ୍ତୁ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('meritus_language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('meritus_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
