export const LOCAL_SCHOLARSHIP_DATA = `id,scholarship_name,provider,provider_type,gender,category,state,income_limit,education_level,eligibility_text,deadline,link
1,Post Matric Scholarship for SC Girls,National Scholarship Portal,Government,Female,SC,All,250000,UG/PG,"Female students of SC category studying post-matric",2026-03-31,https://scholarships.gov.in
2,Post Matric Scholarship for ST Girls,National Scholarship Portal,Government,Female,ST,All,250000,UG/PG,"Female students of ST category studying post-matric",2026-03-31,https://scholarships.gov.in
3,AICTE Pragati Scholarship for Girls,All India Council for Technical Education,Government,Female,All,All,800000,UG,"Girls pursuing technical diploma/degree in AICTE institutes",2026-03-10,https://dte.maharashtra.gov.in/pragati-scholarship-scheme/
4,Kanyashree Prakalpa (Conditional Cash Transfer),Government of West Bengal,Government,Female,All,West Bengal,120000,School,"Girls of West Bengal for continued education and conditional cash transfer",2026-12-31,https://www.wbkanyashree.gov.in/
5,Begum Hazrat Mahal National Scholarship,Ministry of Minority Affairs,Government,Female,Minority,All,200000,UG/PG,"Minority girl students with low family income",2026-04-15,https://scholarships.gov.in
6,National Means-cum-Merit Scholarship (NMMS),Ministry of Education,Government,All,All,All,150000,School,"Merit & means scholarship for economically weaker students (girls eligible)",2026-01-31,https://scholarships.gov.in
7,Kasturba Gandhi Scholarship for Girls,Ministry of Education,Government,Female,All,All,300000,School,"Girls from economically weaker sections studying in schools",2026-02-28,https://scholarships.gov.in
8,UGC PG Scholarship for Women,University Grants Commission,Government,Female,All,All,NA,PG,"Women enrolled in postgraduate courses in recognized universities",2026-03-25,https://www.ugc.ac.in/
9,Tata Trusts Women Higher Education Scholarship,Tata Trusts,Private,Female,All,All,400000,UG,"Women from low-income families pursuing undergraduate studies",2026-03-15,https://www.tatatrusts.org/
10,L'Oréal India For Young Women in Science,L'Oréal India,Private,Female,All,All,600000,UG/PG,"Meritorious female students in science streams with financial constraints",2026-02-20,https://india.loreal.com/
11,Reliance Foundation Education Scholarship,Reliance Foundation,Private,Female,All,All,500000,UG,"Meritorious girl students pursuing higher education",2026-03-18,https://www.ril.com/
12,ONGC Scholarship (SC/ST Girls),Oil and Natural Gas Corporation,Government,Female,SC ST,All,200000,UG,"SC/ST female students with good academic record",2026-03-10,https://ongcindia.com/
13,LIC Golden Jubilee Scholarship for Girls,Life Insurance Corporation,Government/Fund,Female,All,All,300000,UG,"Economically weaker female students pursuing degree courses",2026-03-05,https://licindia.in/
14,Central Sector Scholarship for College Girls,Ministry of Education,Government,Female,All,All,800000,UG,"Meritorious girl students pursuing college education",2026-02-28,https://scholarships.gov.in
15,Saksham (Differently Abled) Scholarship for Girls,AICTE/NSP,Government,Female,All,All,800000,UG/PG,"Differently abled girl students pursuing higher education",2026-03-30,https://scholarships.gov.in
16,Kanyashree-Related Stipend (WB College Girls),Government of West Bengal,Government,Female,All,West Bengal,120000,UG,"Stipend support for college-going girls in West Bengal",2026-12-31,https://www.wbkanyashree.gov.in/
17,Pragati (Maharashtra) Degree/Diploma Girls Scholarship,Directorate of Technical Education Maharashtra,Government,Female,All,Maharashtra,800000,UG,"Female students pursuing technical education in Maharashtra (Pragati)",2026-03-10,https://dte.maharashtra.gov.in/pragati-scholarship-scheme/
18,Savitribai Phule Scholarship for Nomadic Girls,Maharashtra Government,Government,Female,VJNT/SBC,Maharashtra,NA,UG,"Encourage enrollment and reduce dropout of girl students from nomadic communities",2026-03-01,https://myscheme.gov.in
19,Karnataka Sanchi Honnamma Scholarship,Dept. of Collegiate Education Karnataka,Government,Female,All,Karnataka,NA,UG,"Meritorious girl students admitted to first year undergraduate programmes",2026-03-31,https://dce.karnataka.gov.in/info-2/Student%2BScholarships/en
20,Bhagyalakshmi Scheme (Karnataka),Government of Karnataka,Government,Female,All,Karnataka,NA,School,"Financial aid for female children to encourage education",2026-03-31,https://myscheme.gov.in
21,Chief Minister Kanya Sumangala (Mukhyamantri) (Odisha),Govt. of Odisha,Government,Female,All,Odisha,200000,All,"State scheme supporting girl child education and incentives",2026-03-31,https://scholarship.odisha.gov.in
21,Chief Minister Kanya Sumangala (Mukhyamantri) (Odisha),Govt. of Odisha,Government,Female,All,Odisha,200000,All,"State scheme supporting girl child education and incentives",2026-03-31,https://scholarship.odisha.gov.in
22,e-Medhabruti Scholarship (Odisha),Higher Education Dept Govt of Odisha,Government,All,All,Odisha,NA,UG/PG,"Merit-based scholarship for students of Odisha pursuing higher education",2026-03-31,https://scholarship.odisha.gov.in
23,KALIA Scholarship (Krusi Vidya),Agriculture & FE Dept Govt of Odisha,Government,All,All,Odisha,NA,UG/PG,"Scholarship for children of KALIA beneficiaries (farmers) for professional courses",2026-03-31,https://scholarship.odisha.gov.in
24,Gopabandhu Sikhya Sahayata Yojana,Higher Education Dept Odisha,Government,All,All,Odisha,120000,UG/PG,"Financial assistance to students from families of weavers/artisans/fishermen",2026-03-31,https://scholarship.odisha.gov.in
25,Nirman Shramik Kalyan Yojana (Odisha),Odisha Building & Other Construction Workers Welfare Board,Government,All,All,Odisha,NA,All,"Scholarship for children of registered construction workers in Odisha",2026-03-31,https://scholarship.odisha.gov.in
26,Uttar Pradesh Kanya Sumangala Yojana,Government of Uttar Pradesh,Government,Female,All,Uttar Pradesh,300000,All,"Benefits and savings for girl child education in UP",2026-03-31,https://mksy.up.gov.in
27,Tamil Nadu Pudhumai Penn Thittam (Girls Scheme),Government of Tamil Nadu,Government,Female,All,Tamil Nadu,250000,UG/PG,"Assistance to girl students (state-level schemes such as Pudhumai Penn)",2026-03-31,https://tndce.tn.gov.in/Home/scholarship
28,Maharashtra Girls Free Education Scheme,DHE Maharashtra,Government,Female,All,Maharashtra,NA,UG/PG,"Girl's Free Education scheme and scholarships in Maharashtra",2026-08-31,https://dhepune.gov.in/girls-free-education/
29,West Bengal State Merit Scholarship for Girls,West Bengal Government,Government,Female,All,West Bengal,NA,UG/PG,"Merit-based scholarship schemes available for girls in West Bengal",2026-03-31,https://wb.gov.in
30,Kerala Women Scholarship (state & NGO mixes),Kerala State/NPOs,Government/Private,Female,All,Kerala,NA,UG/PG,"State & NGO scholarships for girl students from Kerala",2026-03-30,https://www.education.kerala.gov.in
31,Saksham Scholarship (for Specially Abled) - national,Ministry of Social Justice/NSP,Government,Female,All,All,800000,UG/PG,"Support for specially-abled women students across India",2026-03-30,https://scholarships.gov.in
32,Aditya Birla Scholarship for Women,Aditya Birla Group,Private,Female,All,All,NA,UG/PG,"Meritorious women students enrolled in premier institutions",2026-02-10,https://www.adityabirla.com/
33,Mahindra All India Talent Scholarship (Girls),Mahindra Foundation,Private,Female,All,All,300000,UG,"Girls from economically weak background pursuing diploma or degree",2026-02-15,https://www.mahindra.com/
34,Fair & Lovely (now Glow & Lovely) Foundation Scholarship,Glow & Lovely Foundation,Private,Female,All,All,600000,UG/PG,"Women students pursuing education after class 12",2026-03-20,https://www.gloandlovely.in
35,SBI Youth for India / Scholarship related women programs,State Bank of India Foundation,Private,Female,All,All,NA,UG/PG,"Scholarship and fellowship programs supporting rural women students",2026-04-30,https://www.sbi.co.in/
36,Tata Capital Pankh Scholarship (girls),Tata Capital Foundation,Private,Female,All,All,NA,UG,"Scholarships specifically for girls to continue higher education",2026-04-15,https://www.tatacapital.com/
37,HPCL Girls Scholarship,HPCL CSR,Private,Female,All,All,NA,UG,"Corporate CSR scholarships for girl students by HPCL",2026-03-31,https://www.hindustanpetroleum.com/
38,ONGC Scholarship (Women Professional Courses),ONGC CSR/NSP,Government/Private,Female,All,All,NA,UG/PG,"Support for girls pursuing professional and technical education",2026-03-31,https://www.ongcindia.com/
39,Reliance Foundation - Girl Child Education Program,Reliance Foundation,Private,Female,All,All,NA,UG,"Support and scholarships for girls under Reliance CSR",2026-03-18,https://www.ril.com/
40,Central Sector Scheme of National Fellowship for SC Women,University Grants Commission,Government,Female,SC,All,NA,PG,"Fellowship support for SC women pursuing higher research degrees",2026-03-31,https://www.ugc.ac.in/
41,State Merit Scholarship (Punjab) for Girls,Punjab Government,Government,Female,All,Punjab,NA,UG/PG,"State merit scholarships and schemes for girls",2026-03-31,https://punjab.gov.in
42,Assam State Girl Child Scholarships,Assam Government,Government,Female,All,Assam,NA,School/UG,"Various state schemes supporting girls' education in Assam",2026-03-31,https://assam.gov.in
43,North East Region (Ishan Uday) Special Scholarships (girls),Ministry of Education/NEC,Government,Female,NER states,All,UG/PG,"Scholarships for students (including girls) from North East Region",2026-03-31,https://scholarships.gov.in
44,CBSE Merit Scholarship for Girls,Central Board of Secondary Education,Government,Female,All,All,NA,UG,"CBSE merit scholarship schemes applicable to girl students",2026-03-20,https://www.cbse.gov.in
45,Bhagyashree/State Girl Scholarship (Rajasthan),Rajasthan Government,Government,Female,All,Rajasthan,NA,School/UG,"State-level scholarships and schemes for girls in Rajasthan",2026-03-31,https://rajasthan.gov.in
46,Shramik Kanya/State Education Grants (Chhattisgarh),Chhattisgarh Government,Government,Female,All,Chhattisgarh,NA,School/UG,"State grants and scholarships encouraging girl education",2026-03-31,https://chhattisgarh.nic.in
47,Vidya Lakshmi/Bank-linked Girls Scholarship Programs,Various Banks/NGOs,Private,Female,All,All,NA,UG,"Scholarships and loan-linked scholarships for girls by banking foundations",2026-05-31,https://www.vidyalakshmi.co.in
48,TMF (Teacher/Medical Women Fellowship) State Scholarships,State Health/Education Funds,Government/Fund,Female,All,All,NA,PG/Professional,"State-specific scholarships for women in medical/teaching professions",2026-06-30,https://scholarships.gov.in
49,Indira Gandhi Scholarship for Single Girl Child,Ministry of Women & Child Dev / UGC,Government,Female,All,All,NA,PG,"Scholarship for single girl child pursuing PG",2026-03-30,https://scholarships.gov.in
50,Women in STEM Scholarship (Private Foundations),Multiple Foundations,Private,Female,All,All,NA,UG/PG,"Private foundations offering targeted STEM scholarships for women",2026-04-30,https://buddy4study.com/scholarships/girls
51,State SC/ST Post-Matric Scholarships (various states),State Scholarship Portals,Government,Female,SC ST,Various,200000,UG,"State-level post-matric scholarships for SC/ST girl students (links per state portal)",2026-03-31,https://scholarships.gov.in
52,Minority Girls Scholarship (State-wise),State Minority Welfare Boards,Government,Female,Minority,Various,200000,UG/PG,"State minority girl scholarship programs (apply via state portals/NSP)",2026-04-30,https://scholarships.gov.in
53,Corporate Women Scholarship Consortium (CSR list examples),Various Corporates,Private,Female,All,All,NA,UG/PG,"Collection of corporate scholarships for women (see corporate CSR pages)",2026-05-31,https://collegesimplified.in
54,Local NGO Girls Scholarship (State NGO lists),Various NGOs,Nonprofit,Female,All,All,NA,UG/PG,"Local NGO scholarships for girls (links vary by state NGO pages & aggregators)",2026-05-31,https://buddy4study.com/scholarships/girls
55,Google Generation Scholarship (APAC),Google,Private,Female,All,All,NA,UG,"Women in computer science or related technical fields",2026-05-15,https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac
56,HDFC Bank Parivartan's ECSS Programme,HDFC Bank,Private,All,All,All,250000,School/UG/PG,"Students from COVID-affected or low-income families",2026-09-30,https://www.hdfcbank.com
57,Fulbright-Nehru Master’s Fellowships,USIEF,Government,All,All,All,NA,PG,"Outstanding Indians to pursue master's degrees in the US",2026-05-15,https://www.usief.org.in
58,Sitaram Jindal Foundation Scholarship,Sitaram Jindal Foundation,NGO,All,All,All,250000,School/UG/PG,"Merit-cum-means scholarship for various courses",2026-12-31,https://www.sitaramjindalfoundation.org
59,Kotak Kanya Scholarship,Kotak Education Foundation,Private,Female,All,All,600000,UG,"Meritorious girls from low-income families for professional courses",2026-09-30,https://www.kotak.com
60,L'Oréal India For Young Women In Science Scholarship,L'Oréal India,Private,Female,All,All,600000,UG,"For young women who have passed class 12 and wish to pursue science",2026-10-15,https://www.loreal.com/en/india
61,Glow & Lovely Careers Scholarship,Glow & Lovely Foundation,Private,Female,All,All,600000,UG/PG,"Empowering women to pursue higher education and vocational training",2026-12-15,https://www.glowandlovelycareers.in
62,National Overseas Scholarship for SC/ST,Ministry of Social Justice & Empowerment,Government,All,SC ST,All,800000,PG/PhD,"Financial assistance for low-income students from marginalized communities to study abroad",2026-03-31,https://nosmsje.gov.in
63,Adobe Research Women-in-Technology Scholarship,Adobe,Private,Female,All,All,NA,UG/PG,"Recognizing outstanding female students in computer science",2026-11-01,https://research.adobe.com/scholarship
64,Legrand Empowerment Scholarship,Legrand India,Private,Female,All,All,500000,UG,"Supporting girl students for engineering and architecture courses",2026-08-31,https://www.legrand.co.in
65,Google Women Techmakers Scholars Program,Google,Private,Female,All,All,NA,UG/PG,"Scholarship for women in computer science and technology",Upcoming - Opens April,https://www.womentechmakers.com/scholars
66,Palantir Women in Technology Scholarship,Palantir,Private,Female,All,All,7000,UG,"Supporting women in computer science, engineering and technical fields",Upcoming - Opens Sept,https://www.palantir.com/students/scholarships/
67,Society of Women Engineers (SWE) Scholarships,SWE,Private,Female,All,All,NA,UG/PG,"Scholarships for women pursuing ABET-accredited programs in engineering",Upcoming - Opens Dec,https://swe.org/scholarships/
68,AAUW International Fellowships,AAUW,Private,Female,All,Global,NA,PG/PhD,"Support for women pursuing full-time study or research in the US",Upcoming - Opens Aug,https://www.aauw.org/resources/programs/fellowships-grants/
69,Schlumberger Foundation Faculty for the Future,Schlumberger Foundation,Private,Female,All,Global,NA,PhD,"Fellowships for women from developing countries for PhD/Post-doc in STEM",Upcoming - Opens Sept,https://www.facultyforthefuture.net/
70,British Council Scholarships for Women in STEM,British Council,Government,Female,All,Global,NA,PG,"Scholarships for women from various countries to study STEM in the UK",Upcoming - Opens Jan,https://www.britishcouncil.org/study-work-abroad/in-uk/scholarships-women-stem
71,Odisha State Research Fellowship (OSRF),Govt of Odisha,Government,All,All,Odisha,NA,PhD,"Fellowship for research scholars in Odisha",Upcoming - Opens July,https://scholarship.odisha.gov.in
72,Prerana Post Matric Scholarship (Upcoming Cycle),Govt of Odisha,Government,SC ST OBC,All,Odisha,250000,UG/PG,"Post-matric scholarship for marginalized communities in Odisha",Upcoming - Opens Sept,https://scholarship.odisha.gov.in
73,Medhabruti (New Cycle),Govt of Odisha,Government,All,All,Odisha,NA,UG/PG,"Merit-based scholarship for Odisha students",Upcoming - Opens Oct,https://scholarship.odisha.gov.in
74,Gates Cambridge Scholarship,Bill and Melinda Gates Foundation,Private,All,All,Global,NA,PG/PhD,"Full-cost scholarship for outstanding applicants from outside the UK to pursue a full-time postgraduate degree at the University of Cambridge",2026-10-15,https://www.gatescambridge.org/
75,Chevening Scholarships,UK Government,Government,All,All,Global,NA,PG,"Fully-funded master's degree scholarships for international students to study in the UK",2026-11-05,https://www.chevening.org/
76,Fulbright Foreign Student Program,US Government,Government,All,All,Global,NA,PG/PhD,"Enables graduate students, young professionals and artists from abroad to study and conduct research in the United States",2026-10-31,https://foreign.fulbrightonline.org/
77,Erasmus Mundus Joint Masters,European Union,Government,All,All,Global,NA,PG,"Prestigious, integrated, international study programmes, jointly delivered by an international consortium of higher education institutions",2026-02-15,https://erasmus-plus.ec.europa.eu/
78,Australia Awards Scholarships,Australian Government,Government,All,All,Global,NA,UG/PG/PhD,"Long-term awards administered by the Department of Foreign Affairs and Trade to contribute to the development needs of Australia's partner countries",2026-04-30,https://www.dfat.gov.au/people-to-people/australia-awards
79,DAAD Scholarships,German Academic Exchange Service,Government,All,All,Global,NA,PG/PhD,"Scholarships for international students to study in Germany",2026-07-15,https://www.daad.de/en/
80,Eiffel Excellence Scholarship Program,French Ministry for Europe and Foreign Affairs,Government,All,All,Global,NA,PG/PhD,"Attracts top foreign students to enroll in masters and PhD courses in France",2026-01-10,https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence
81,Swiss Government Excellence Scholarships,Swiss Government,Government,All,All,Global,NA,PG/PhD,"Aimed at young researchers from abroad who have completed a master's degree or PhD",2026-11-30,https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html
82,Knight-Hennessy Scholars,Stanford University,Private,All,All,Global,NA,PG/PhD,"Fully-funded fellowship for graduate study at Stanford University",2026-10-09,https://knight-hennessy.stanford.edu/
83,Rhodes Scholarships,Rhodes Trust,Private,All,All,Global,NA,PG/PhD,"Oldest and perhaps most prestigious international scholarship programme, enabling outstanding young people from around the world to study at the University of Oxford",2026-08-01,https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/
84,Schwarzman Scholars,Tsinghua University,Private,All,All,Global,NA,PG,"Fully-funded master's program at Tsinghua University in Beijing, designed to build a global community of future leaders",2026-09-12,https://www.schwarzmanscholars.org/
85,Clarendon Fund Scholarships,University of Oxford,Private,All,All,Global,NA,PG/PhD,"Major graduate scholarship scheme at the University of Oxford, offering around 140 new scholarships every year",2026-01-20,https://www.ox.ac.uk/clarendon
86,Vanier Canada Graduate Scholarships,Government of Canada,Government,All,All,Global,NA,PhD,"Attracts and retains world-class doctoral students and helps establish Canada as a global centre of excellence in research and higher learning",2026-11-01,https://vanier.gc.ca/en/home-accueil.html
87,Banting Postdoctoral Fellowships,Government of Canada,Government,All,All,Global,NA,Post-Doc,"Provides funding to the very best postdoctoral applicants, both nationally and internationally",2026-09-20,https://banting.fellowships-bourses.gc.ca/en/home-accueil.html
88,Aga Khan Foundation International Scholarship Programme,Aga Khan Foundation,Private,All,All,Global,NA,PG/PhD,"Provides a limited number of scholarships each year for postgraduate studies to outstanding students from select developing countries",2026-03-31,https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation/international-scholarship-programme
89,Joint Japan World Bank Graduate Scholarship Program,World Bank,Government,All,All,Global,NA,PG,"Scholarships to students from developing countries to pursue master's degrees at participating universities around the world",2026-05-24,https://www.worldbank.org/en/programs/scholarships
90,OPEC Fund for International Development (OFID) Scholarship,OFID,Government,All,All,Global,NA,PG,"Sponsors outstanding young students from developing countries who wish to pursue a Master's degree in a development-related field",2026-04-15,https://opecfund.org/
91,Heinrich Böll Foundation Scholarships,Heinrich Böll Foundation,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in Germany",2026-03-01,https://www.boell.de/en/scholarships
92,Konrad-Adenauer-Stiftung Scholarships,Konrad-Adenauer-Stiftung,Private,All,All,Global,NA,PG/PhD,"Scholarships for international students to study in Germany",2026-07-15,https://www.kas.de/en/web/begabtenfoerderung-und-kultur/foreign-students
93,Friedrich Ebert Foundation Scholarships,Friedrich Ebert Foundation,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in Germany",2026-11-30,https://www.fes.de/studienfoerderung/bewerbung
94,Amartya Sen Scholarship,LSE,Private,All,All,Global,NA,PG,"Scholarship for students from India to study at the London School of Economics",2026-04-25,https://www.lse.ac.uk/study-at-lse/Graduate/fees-and-funding
95,Inlaks Scholarships,Inlaks Shivdasani Foundation,Private,All,All,Global,NA,PG,"Scholarships for young Indians to study at top American, European and UK institutions",2026-03-30,https://www.inlaksfoundation.org/
96,Narotam Sekhsaria Scholarship,Narotam Sekhsaria Foundation,Private,All,All,Global,NA,PG,"Interest-free loan scholarships for Indian students pursuing postgraduate studies in India and abroad",2026-03-15,https://pg.nsfoundation.co.in/
97,JN Tata Endowment Loan Scholarship,JN Tata Endowment,Private,All,All,Global,NA,PG/PhD,"Loan scholarships for Indians for higher studies abroad",2026-03-15,https://www.jntataendowment.org/
98,K.C. Mahindra Scholarships for Post-Graduate Studies Abroad,K.C. Mahindra Education Trust,Private,All,All,Global,NA,PG,"Interest-free loan scholarships for postgraduate studies abroad",2026-03-31,https://www.kcmet.org/
99,Lady Meherbai D. Tata Education Trust Scholarship,Lady Meherbai D. Tata Education Trust,Private,Female,All,Global,NA,PG,"Scholarships for Indian women graduates for higher studies abroad",2026-04-15,https://www.tatatrusts.org/
100,Aga Khan Foundation Scholarship,Aga Khan Foundation,Private,All,All,Global,NA,PG/PhD,"Scholarships for postgraduate studies to outstanding students from developing countries",2026-03-31,https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation/international-scholarship-programme
101,Dr. Manmohan Singh Scholarships,St. John's College Cambridge,Private,All,All,Global,NA,PhD,"Scholarships for Indian students to pursue doctoral studies at St. John's College, Cambridge",2026-01-15,https://www.joh.cam.ac.uk/
102,Felix Scholarships,Felix Scholarship Trust,Private,All,All,Global,NA,PG/PhD,"Scholarships for Indian students and students from other developing countries to pursue graduate studies at Oxford, Reading and SOAS",2026-01-30,https://www.felixscholarship.org/
103,Commonwealth Scholarships for Developing Commonwealth Countries,UK Government,Government,All,All,Global,NA,PG/PhD,"Scholarships for students from developing Commonwealth countries to study in the UK",2026-10-15,https://cscuk.fcdo.gov.uk/
104,Great Scholarships,British Council,Government,All,All,Global,NA,PG,"Scholarships for students from 14 countries to study in the UK",2026-05-31,https://study-uk.britishcouncil.org/scholarships/great-scholarships
105,Charles Wallace India Trust Scholarships,Charles Wallace India Trust,Private,All,All,Global,NA,PG/Research,"Scholarships for Indians in the early to mid stages of their careers to spend time in the UK",2026-12-31,https://www.charleswallaceindiatrust.com/
106,Saltire Scholarships,Scottish Government,Government,All,All,Global,NA,PG,"Scholarships for students from select countries to study in Scotland",2026-05-28,https://www.scotland.org/study/saltire-scholarships
107,Eiffel Excellence Scholarship Program,French Ministry for Europe and Foreign Affairs,Government,All,All,Global,NA,PG/PhD,"Scholarships for international students to enroll in masters and PhD courses in France",2026-01-10,https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence
108,Charpak Scholarship Program,French Embassy in India,Government,All,All,Global,NA,UG/PG/Research,"Scholarships for Indian students to study in France",2026-04-15,https://www.inde.campusfrance.org/charpak-scholarships
109,Raman-Charpak Fellowship,Indo-French Centre for the Promotion of Advanced Research,Government,All,All,Global,NA,PhD,"Fellowship for Indian and French PhD students to carry out part of their research work in the other country",2026-05-31,https://www.cefipra.org/
110,Orange Tulip Scholarship,Nuffic Neso India,Government,All,All,Global,NA,UG/PG,"Scholarships for Indian students to study in the Netherlands",2026-04-01,https://www.nesoindia.org/scholarships/orange-tulip-scholarship-programme
111,Holland Scholarship,Dutch Ministry of Education,Government,All,All,Global,NA,UG/PG,"Scholarship for international students from outside the EEA to study in the Netherlands",2026-05-01,https://www.studyinnl.org/finances/holland-scholarship
112,Swedish Institute Scholarships for Global Professionals,Swedish Institute,Government,All,All,Global,NA,PG,"Scholarships for international students to study in Sweden",2026-02-28,https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/
113,Danish Government Scholarships for Highly Qualified Non-EU/EEA Students,Danish Ministry of Higher Education and Science,Government,All,All,Global,NA,PG,"Scholarships for international students to study in Denmark",2026-09-01,https://studyindenmark.dk/study-options/tuition-fees-scholarships
114,Italian Government Scholarships for Foreign Students,Ministry of Foreign Affairs and International Cooperation,Government,All,All,Global,NA,PG/PhD,"Scholarships for foreign students to study in Italy",2026-06-09,https://studyinitaly.esteri.it/en/call-for-procedure
115,Invest Your Talent in Italy,Ministry of Foreign Affairs and International Cooperation,Government,All,All,Global,NA,PG,"Scholarships for students from select countries to study in Italy",2026-03-01,https://investyourtalentapplication.esteri.it/sitoinvestyourtalentapplication/progetto.asp
116,Spanish Government Scholarships,Ministry of Education,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in Spain",2026-05-15,https://www.educacionyfp.gob.es/servicios-al-ciudadano/catalogo/estudiantes/becas-ayudas/para-estudiar.html
117,MEXT Scholarships,Ministry of Education Japan,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in Japan",2026-05-31,https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html
118,JASSO Scholarships,Japan Student Services Organization,Government,All,All,Global,NA,UG/PG,"Scholarships for international students to study in Japan",2026-04-30,https://www.jasso.go.jp/en/study_j/scholarships/index.html
119,Korean Government Scholarship Program,NIIED,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in South Korea",2026-03-15,https://www.studyinkorea.go.kr/en/sub/gks/all.do
120,Taiwan Scholarship,Ministry of Education Taiwan,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students to study in Taiwan",2026-03-31,https://taiwanscholarship.moe.gov.tw/web/engb02-01.html
121,Singapore International Graduate Award (SINGA),A*STAR,Government,All,All,Global,NA,PhD,"Award for international students to pursue PhD studies in Singapore",2026-06-01,https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa
122,Hong Kong PhD Fellowship Scheme,Research Grants Council,Government,All,All,Global,NA,PhD,"Fellowship for international students to pursue PhD studies in Hong Kong",2026-12-01,https://cerg1.ugc.edu.hk/hkpfs/index.html
123,New Zealand Scholarships,Ministry of Foreign Affairs and Trade,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students from developing countries to study in New Zealand",2026-02-28,https://www.nzscholarships.govt.nz/
124,Endeavour Postgraduate Scholarship Awards,Australian Government,Government,All,All,Global,NA,PG/PhD,"Scholarships for international students to undertake postgraduate study in Australia",2026-06-30,https://internationaleducation.gov.au/endeavour%20program/scholarships-and-fellowships/pages/default.aspx
125,Destination Australia Scholarships,Australian Government,Government,All,All,Global,NA,UG/PG/PhD,"Scholarships for domestic and international students to study in regional Australia",2026-01-31,https://www.education.gov.au/destination-australia
126,Banting Postdoctoral Fellowships,Government of Canada,Government,All,All,Global,NA,Post-Doc,"Fellowships for top-tier postdoctoral researchers, both nationally and internationally",2026-09-20,https://banting.fellowships-bourses.gc.ca/en/home-accueil.html
127,Vanier Canada Graduate Scholarships,Government of Canada,Government,All,All,Global,NA,PhD,"Scholarships for world-class doctoral students",2026-11-01,https://vanier.gc.ca/en/home-accueil.html
128,Trudeau Foundation Scholarships,Pierre Elliott Trudeau Foundation,Private,All,All,Global,NA,PhD,"Scholarships for doctoral students in the social sciences and humanities",2026-12-21,https://www.trudeaufoundation.ca/scholarship
129,Lester B. Pearson International Scholarships,University of Toronto,Private,All,All,Global,NA,UG,"Scholarships for exceptional international students to study at the University of Toronto",2026-01-15,https://future.utoronto.ca/pearson/about/
130,Karen McKellin International Leader of Tomorrow Award,University of British Columbia,Private,All,All,Global,NA,UG,"Award for international undergraduate students who demonstrate superior academic achievement",2026-11-15,https://you.ubc.ca/financial-planning/scholarships-awards-international-students/international-scholars/
131,Humber International Entrance Scholarships,Humber College,Private,All,All,Global,NA,UG/PG,"Scholarships for new international students",2026-05-31,https://international.humber.ca/student-services/managing-your-finances/scholarships-awards.html
132,York University International Student Scholarship Program,York University,Private,All,All,Global,NA,UG,"Scholarships for international students with an excellent academic record",2026-02-15,https://futurestudents.yorku.ca/financialsupport
133,Carleton University Entrance Scholarships for International Students,Carleton University,Private,All,All,Global,NA,UG,"Scholarships for international students admitted to Carleton University",2026-06-15,https://admissions.carleton.ca/scholarships/
134,University of Calgary International Entrance Scholarship,University of Calgary,Private,All,All,Global,NA,UG,"Scholarship for international students entering their first year of undergraduate study",2026-12-01,https://www.ucalgary.ca/registrar/finances/awards/international
135,University of Winnipeg President's Scholarship for World Leaders,University of Winnipeg,Private,All,All,Global,NA,UG/PG,"Scholarships for international students entering any of the University's divisions",2026-06-01,https://www.uwinnipeg.ca/awards/international-students.html
136,Concordia University International Tuition Award of Excellence,Concordia University,Private,All,All,Global,NA,UG/PG/PhD,"Award for international students to pay tuition at the Quebec rate",2026-03-01,https://www.concordia.ca/admissions/tuition-fees/how-fees-are-billed/undergraduate/exemptions.html
137,Dalhousie University Scholarships,Dalhousie University,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students",2026-03-01,https://www.dal.ca/admissions/money_matters/awards-financial-aid/scholarships.html
138,University of Saskatchewan International Excellence Awards,University of Saskatchewan,Private,All,All,Global,NA,UG,"Awards for international students based on academic achievement",2026-02-15,https://admissions.usask.ca/money/scholarships.php
139,McGill University Entrance Scholarships,McGill University,Private,All,All,Global,NA,UG,"Scholarships for first-time university students",2026-01-21,https://www.mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships
140,University of Alberta International Promise Award,University of Alberta,Private,All,All,Global,NA,UG,"Award for international students based on academic excellence",2026-01-11,https://www.ualberta.ca/admissions/international/tuition-and-scholarships/scholarships-and-awards/index.html
141,Simon Fraser University Financial Aid and Awards,Simon Fraser University,Private,All,All,Global,NA,UG/PG/PhD,"Various scholarships and awards for international students",2026-04-30,https://www.sfu.ca/students/financialaid/international.html
142,Western University International President's Entrance Scholarships,Western University,Private,All,All,Global,NA,UG,"Scholarships for outstanding international students",2026-02-14,https://registrar.uwo.ca/student_finances/scholarships_awards/international_students.html
143,University of Waterloo International Student Entrance Scholarships,University of Waterloo,Private,All,All,Global,NA,UG,"Scholarships for international students admitted to Year One of an undergraduate degree program",2026-04-15,https://uwaterloo.ca/future-students/financing/scholarships
144,Queen's University International Admission Scholarships,Queen's University,Private,All,All,Global,NA,UG,"Scholarships for international students entering their first year of study",2026-02-15,https://www.queensu.ca/studentawards/admission-awards/international-students
145,McMaster University International Scholarships,McMaster University,Private,All,All,Global,NA,UG,"Scholarships for international students",2026-02-21,https://registrar.mcmaster.ca/financial-aid/scholarships/
146,University of Ottawa International Admission Scholarship,University of Ottawa,Private,All,All,Global,NA,UG,"Scholarship for international students admitted to an undergraduate program",2026-03-31,https://www.uottawa.ca/study/fees-financial-support/scholarships-awards-overview
147,Laval University Scholarships,Laval University,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students",2026-03-15,https://www.ulaval.ca/en/future-students/scholarships-and-financial-aid
148,University of Montreal Scholarships,University of Montreal,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students",2026-02-01,https://admission.umontreal.ca/en/student-info/tools-and-tips/scholarships-and-financial-aid/
149,Sherbrooke University Scholarships,Sherbrooke University,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students",2026-03-01,https://www.usherbrooke.ca/etudiants/finances/bourses/
150,UQAM Scholarships,UQAM,Private,All,All,Global,NA,UG/PG/PhD,"Scholarships for international students",2026-04-01,https://bourses.uqam.ca/
151,Fulbright-Nehru Master's Fellowship,USIEF,Government,All,All,Global,NA,Master's,"Indian citizens with 3 yrs work experience",2026-07-15,https://www.usief.org.in/
152,Fulbright-Nehru Doctoral Research Fellowship,USIEF,Government,All,All,Global,NA,PhD,"Indian citizens enrolled in PhD",2026-07-15,https://www.usief.org.in/
153,Google PhD Fellowship 2026,Google,Private,All,All,Global,NA,PhD,"CS and related fields",2026-04-30,https://research.google/outreach/phd-fellowship/
154,GREAT Scholarships 2026,British Council,Government,All,All,Global,NA,Master's,"Indian passport holders",2026-05-31,https://study-uk.britishcouncil.org/scholarships/great-scholarships
155,University of Manchester Global Futures Scholarship,University of Manchester,Private,All,All,Global,NA,UG/PG,"International incl. India",2026-05-31,https://www.manchester.ac.uk/study/international/finance-and-scholarships/funding/
156,Imperial College London – India Future Leaders Scholarship,Imperial College London,Private,All,All,Global,NA,Master's,"Indian students with offer from Imperial",2026-05-31,https://www.imperial.ac.uk/study/fees-and-funding/scholarships/
157,DAAD Helmut-Schmidt Programme,DAAD,Government,All,All,Global,NA,Master's,"Indian students",2026-10-31,https://www.daad.de/en/
158,DAAD Development-Related Postgraduate Courses,DAAD,Government,All,All,Global,NA,Master's,"All fields",2026-10-31,https://www.daad.de/en/
159,MEXT Scholarship,MEXT,Government,All,All,Global,NA,UG/PG/PhD,"All fields, Open to Indians",2026-05-31,https://www.mext.go.jp/en/
160,Chinese Government Scholarship (CSC) 2026,CSC,Government,All,All,Global,NA,UG/PG/PhD,"All fields",2026-04-30,https://www.campuschina.org/
161,Türkiye Bursları (Turkish Government Scholarship),Turkish Government,Government,All,All,Global,NA,UG/PG/PhD,"All fields",2027-01-31,https://www.turkiyeburslari.gov.tr/
162,Global Korea Scholarship (GKS/KGSP) 2026,NIIED,Government,All,All,Global,NA,UG/PG/PhD,"All fields",2026-04-30,https://www.studyinkorea.go.kr/
163,Stipendium Hungaricum 2026–27,Hungarian Government,Government,All,All,Global,NA,UG/PG/PhD,"All fields",2026-01-15,https://stipendiumhungaricum.hu/
164,Vanier Canada Graduate Scholarship,Government of Canada,Government,All,All,Global,NA,PhD,"Indian students nominated by Canadian university",2026-11-01,https://vanier.gc.ca/en/home-accueil.html
165,Lester B. Pearson International Scholarship,University of Toronto,Private,All,All,Global,NA,UG,"International incl. India",2026-11-30,https://future.utoronto.ca/pearson/about/
166,Rotary Peace Fellowship 2026,Rotary International,Private,All,All,Global,NA,Master's,"Peace & development fields",2026-05-15,https://www.rotary.org/en/our-programs/peace-fellowships
167,Aga Khan Foundation International Scholarship,Aga Khan Foundation,Private,All,All,Global,NA,Master's,"Developing countries incl. India",2027-03-31,https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation/international-scholarship-programme
168,National Overseas Scholarship (NOS),Ministry of Social Justice,Government,All,SC/ST/OBC,Global,800000,Master's/PhD,"SC/ST/OBC/De-notified tribes",2026-05-31,https://nosmsje.gov.in/
169,Dr. Ambedkar Overseas Vidya Nidhi Scholarship,Ministry of Social Justice,Government,All,SC/OBC,Global,800000,UG/PG,"SC/OBC students",2026-04-30,https://socialjustice.gov.in/
170,Maulana Azad National Fellowship (MANF),Ministry of Minority Affairs,Government,All,Minority,National,NA,PhD,"Six minority communities in India",Rolling,https://minorityaffairs.gov.in/
171,Prime Minister's Scholarship Scheme (PMSS),Kendriya Sainik Board,Government,All,All,National,NA,UG,"Wards of ex-servicemen and coast guard",Rolling,https://ksb.gov.in/
172,Ishan Uday – Special Scholarship for North East,UGC,Government,All,All,National,450000,UG,"Students from North East India studying elsewhere",2026-10-31,https://scholarships.gov.in/
173,Central Sector Scholarship Scheme,Ministry of Education,Government,All,All,National,450000,UG/PG,"Top 20th percentile of Class 12",2026-10-31,https://scholarships.gov.in/
174,AICTE Pragati Scholarship (Girls),AICTE,Government,Female,All,National,800000,UG,"Girl students in AICTE-approved institutions",2026-11-30,https://www.aicte-india.org/
175,AICTE Saksham Scholarship (Specially Abled),AICTE,Government,All,All,National,800000,UG,"Differently abled students",2026-11-30,https://www.aicte-india.org/
176,Inlaks Shivdasani Foundation Scholarship,Inlaks Shivdasani Foundation,Private,All,All,Global,NA,Master's/Research,"Indian citizens under 30 for USA/UK/Europe",2027-01-31,https://www.inlaksfoundation.org/
177,JN Tata Endowment Loan Scholarship,JN Tata Endowment,Private,All,All,Global,NA,PG/PhD,"Indian students pursuing higher studies abroad",2026-11-30,https://www.jntataendowment.org/
178,Tata Scholarship (Cornell University),Cornell University,Private,All,All,Global,NA,UG,"Indian students at Cornell",2026-11-30,https://admissions.cornell.edu/apply/international-students/tata-scholarship
179,HDFC Bank Parivartan's ECS (Eklavya) Scholarship,HDFC Bank,Private,All,All,National,250000,UG/PG,"Economically weaker students in India",Rolling,https://www.hdfcbank.com/
180,Sitaram Jindal Scholarship,Sitaram Jindal Foundation,Private,All,All,National,250000,UG/PG/PhD,"Students with annual family income < ₹2.5 lakh",Rolling,https://www.sitaramjindalfoundation.org/
181,Chevening Scholarships 2027–28,UK Government,Government,All,All,Global,NA,Master's,"Fully funded Master's (UK)",2026-11-05,https://www.chevening.org/
182,Rhodes Scholarship 2027,Rhodes Trust,Private,All,All,Global,NA,Graduate,"Full Oxford funding",2026-07-31,https://www.rhodeshouse.ox.ac.uk/
183,Fulbright US Student Program 2027–28,US Government,Government,All,All,Global,NA,Master's/PhD,"Fully funded Master's / PhD (USA)",2026-10-31,https://us.fulbrightonline.org/
184,DAAD Scholarship 2027,DAAD,Government,All,All,Global,NA,Master's/PhD,"Fully funded Master's / PhD (Germany)",2026-10-31,https://www.daad.de/en/
185,Erasmus Mundus 2027,European Union,Government,All,All,Global,NA,Master's,"Fully funded Master's (Europe)",2026-02-15,https://erasmus-plus.ec.europa.eu/
186,Commonwealth Scholarships 2027,UK Government,Government,All,All,Global,NA,Master's/PhD,"Fully funded Master's / PhD (UK)",2026-10-15,https://cscuk.fcdo.gov.uk/
187,Australia Awards 2027,Australian Government,Government,All,All,Global,NA,Master's,"Fully funded Master's",2027-04-30,https://www.dfat.gov.au/people-to-people/australia-awards
188,Turkish Government Scholarship 2027,Turkish Government,Government,All,All,Global,NA,UG/PG/PhD,"Fully funded UG/Master's/PhD (Turkey)",2027-02-20,https://www.turkiyeburslari.gov.tr/
189,Gates Cambridge 2027,Bill and Melinda Gates Foundation,Private,All,All,Global,NA,Master's/PhD,"Full Cambridge funding",2026-10-15,https://www.gatescambridge.org/
190,Swiss Government Excellence Scholarships 2027,Swiss Government,Government,All,All,Global,NA,Master's/PhD,"Full funding + CHF stipend",2026-11-30,https://www.sbfi.admin.ch/
191,Eiffel Excellence Scholarship Program 2027,French Ministry for Europe and Foreign Affairs,Government,All,All,Global,NA,Master's/PhD,"Full funding for Master's/PhD in France",2026-01-10,https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence
192,New Zealand Development Scholarships 2027,New Zealand Government,Government,All,All,Global,NA,Master's/PhD,"Full funding for students from developing countries",2026-02-28,https://www.nzscholarships.govt.nz/
193,Swedish Institute Scholarships for Global Professionals 2027,Swedish Institute,Government,All,All,Global,NA,Master's,"Full funding for Master's in Sweden",2026-02-15,https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/
194,VLIR-UOS Training and Masters Scholarships 2027,VLIR-UOS,Government,All,All,Global,NA,Master's,"Full funding for Master's in Belgium",2026-03-01,https://www.vliruos.be/en/scholarships/6
195,Orange Knowledge Programme 2027,Nuffic,Government,All,All,Global,NA,Master's,"Full funding for Master's in Netherlands",2026-03-30,https://www.studyinholland.nl/finances/orange-knowledge-programme
196,Boustany Foundation MBA Scholarship 2027,Boustany Foundation,Private,All,All,Global,NA,Master's,"Scholarship for MBA at Cambridge University",2026-05-15,https://boustany-foundation.org/scholarship-programs/mba-cambridge/
197,Weidenfeld-Hoffmann Scholarships and Educational Programme 2027,University of Oxford,Private,All,All,Global,NA,Master's,"Full funding for Master's at Oxford",2026-01-20,https://www.ox.ac.uk/admissions/graduate/fees-and-funding/fees-funding-and-scholarship-search/weidenfeld-hoffmann-scholarships-and-educational-programme
198,Joint Japan World Bank Graduate Scholarship Program 2027,World Bank,Government,All,All,Global,NA,Master's,"Full funding for Master's in development-related fields",2026-05-24,https://www.worldbank.org/en/programs/scholarships
199,ADB-Japan Scholarship Program 2027,Asian Development Bank,Government,All,All,Global,NA,Master's,"Full funding for Master's in economics, management, science, and technology",2026-06-30,https://www.adb.org/site/careers/japan-scholarship-program/main
200,Rotary Foundation Global Grant Scholarships 2027,Rotary Foundation,Private,All,All,Global,NA,Master's/PhD,"Funding for graduate-level coursework or research",2026-06-30,https://www.rotary.org/en/our-programs/scholarships
`;
